{
	"_Type": "Action.Type.ToastMessage",
	"OnSuccess": "/SmartInspections/Actions/OData/UploadOfflineSAM.action",
	"ShowActivityIndicator": true,
	"Message": "$(L,sync_success)",
	"Duration": 3,
	"IsIconHidden": false,
	"Animated": true,
	"MaxNumberOfLines": 2
}