{
	"_Type": "Action.Type.OfflineOData.Upload",
	"ActionResult": {
		"_Name": "result"
	},
	"OnFailure": "/SAPAssetManager/Rules/Sync/OnUploadFailure.js",
	"OnSuccess": "/SmartInspections/Actions/OData/UploadOfflineSAM.action",
	"Service": "/SAPAssetManager/Services/AssetManager.service"
}