{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "CloseWorkOrderToComplete"
	},
	"Message": "Please Close the Smart Inspections Order to COMPLETE ",
	"Title": "Close Smart Inspections",
	"OKCaption": "OK"
}