{
	"_Type": "Action.Type.ClosePage",
	"ActionResult": {
		"_Name": "EXListMICListClose"
	},
	"OnSuccess": "/SmartInspections/Actions/EXChangedConf.action",
	"DismissModal": "Action.Type.ClosePage.Canceled",
	"CancelPendingActions": true
}