{
	"_Type": "Action.Type.ClosePage",
	"ActionResult": {
		"_Name": "EXListClose"
	},
	"OnSuccess": "/SmartInspections/Actions/EXListMICListClose.action",
	"DismissModal": "Action.Type.ClosePage.Canceled",
	"CancelPendingActions": true
}