{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "result"
	},
	"OnFailure": "/SmartInspections/Actions/InspectionCharacteristic_CreateEntity_ErrorMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Saving in-progress...",
	"Target": {
		"EntitySet": "InspectionCharacteristicDetailsSet",
		"Service": "/SmartInspections/Services/SAM.service"
	},
	"Properties": {
		"AddInWoSnap": "{AddInWoSnap}",
		"IsAdhocAdded": "{IsAdhocAdded}",
		"IsDescopeUpdated": "{IsDescopeUpdated}",
		"IsExisting": "{IsExisting}",
		"IsUpdReq": "{IsUpdReq}",
		"IsUpdSuccess": "{IsUpdSuccess}",
		"NotFoundAdhoc": "{NotFoundAdhoc}",
		"NumberOfCharacters": "{NumberOfCharacters}",
		"NumberOfDecimals": "{NumberOfDecimals}",
		"Index": "{Index}",
		"ListCounter": "{ListCounter}",
		"MaxIndex": "{MaxIndex}",
		"NumberOfSamples": "{NumberOfSamples}",
		"CharacteristicValue1Desc": "{CharacteristicValue1Desc}",
		"CharacteristicValue1": "{CharacteristicValue1}",
		"CharacteristicValue2Desc": "{CharacteristicValue2Desc}",
		"CharacteristicValue2": "{CharacteristicValue2}",
		"CodeGroup": "{CodeGroup}",
		"DateValueMaintained": "{DateValueMaintained}",
		"DefectCode": "{DefectCode}",
		"DefectCodeGroup": "{DefectCodeGroup}",
		"DescopedBy": "{DescopedBy}",
		"Equipment": "{Equipment}",
		"EquipmentDescription": "{EquipmentDescription}",
		"EquipmentFlag": "{EquipmentFlag}",
		"FixedValuesResult": "{FixedValuesResult}",
		"FunctionalLocation": "{FunctionalLocation}",
		"FunctionalLocationDesc": "{FunctionalLocationDesc}",
		"InspectionCharacteristicNumb": "{InspectionCharacteristicNumb}",
		"InspectionLotNumber": "{InspectionLotNumber}",
		"InspectionSampleNumber": "{InspectionSampleNumber}",
		"InspectionShortText": "{InspectionShortText}",
		"InspectionTypes": "{InspectionTypes}",
		"LongText": "{LongText}",
		"LowerLimit": "{LowerLimit}",
		"LowerPlausibleLimit": "{LowerPlausibleLimit}",
		"MicDescopeDesc": "{MicDescopeDesc}",
		"MicDescopeType": "{MicDescopeType}",
		"MicLongText": "{MicLongText}",
		"MicNumber": "{MicNumber}",
		"MicPlant": "{MicPlant}",
		"MicShortText": "{MicShortText}",
		"MicType": "{MicType}",
		"MultipleSample": "{MultipleSample}",
		"NodeNumber": "{NodeNumber}",
		"OperationNumber": "{OperationNumber}",
		"OperationShortText": "{OperationShortText}",
		"OrderDescription": "{OrderDescription}",
		"OrderNumber": "{OrderNumber}",
		"OrderType": "{OrderType}",
		"PlausibleMessageType": "{PlausibleMessageType}",
		"Result": "{Result}",
		"SampleCriteria": "{SampleCriteria}",
		"SampleReading1": "{SampleReading1}",
		"SampleReading10": "{SampleReading10}",
		"SampleReading11": "{SampleReading11}",
		"SampleReading12": "{SampleReading12}",
		"SampleReading13": "{SampleReading13}",
		"SampleReading14": "{SampleReading14}",
		"SampleReading15": "{SampleReading15}",
		"SampleReading16": "{SampleReading16}",
		"SampleReading17": "{SampleReading17}",
		"SampleReading18": "{SampleReading18}",
		"SampleReading19": "{SampleReading19}",
		"SampleReading2": "{SampleReading2}",
		"SampleReading20": "{SampleReading20}",
		"SampleReading3": "{SampleReading3}",
		"SampleReading4": "{SampleReading4}",
		"SampleReading5": "{SampleReading5}",
		"SampleReading6": "{SampleReading6}",
		"SampleReading7": "{SampleReading7}",
		"SampleReading8": "{SampleReading8}",
		"SampleReading9": "{SampleReading9}",
		"SamplingProcedure": "{SamplingProcedure}",
		"SelectedSet": "{SelectedSet}",
		"SortNumber": "{SortNumber}",
		"Status": "{Status}",
		"TargetValue": "{TargetValue}",
		"TechnicalObject": "{TechnicalObject}",
		"TechnicalObjectDescription": "{TechnicalObjectDescription}",
		"UnitOfMeasure": "{UnitOfMeasure}",
		"UpperLimit": "{UpperLimit}",
		"UpperPlausibleLimit": "{UpperPlausibleLimit}",
		"Version": "{Version}",
		"DeleteFromWoSnap": "{DeleteFromWoSnap}",
		"EXCallMode": "{EXCallMode}"
	},
	"RequestOptions": {
		"RemoveCreatedEntityAfterUpload": true
	}
}