{
	"CancelCaption": "CANCEL",
	"Message": "/SmartInspections/Rules/HistoryDetails_MessageText.js",
	"OKCaption": "OK",
	"OnOK": "/SmartInspections/Actions/NavToInspectionHistoryDetailsList.action",
	"Title": "/SmartInspections/Rules/HistoryDetails_MessageCodeText.js",
	"_Type": "Action.Type.Message"
}