{
	"_Type": "Action.Type.Navigation",
	"PageToOpen": "/SmartInspections/Pages/InspCharDescopeTypeDetailsList.page",
	"ClearHistory": false,
	"ModalPage": true,
	"ModalPageFullscreen": true,
	"NavigationType": "Cross"
}