{
	"_Type": "Action.Type.Navigation",
	"PageToOpen": "/SmartInspections/Pages/QualitativeYN.page",
	"ClearHistory": true,
	"ModalPage": true,
	"ModalPageFullscreen": true,
	"NavigationType": "Cross"
}