{
	"CancelCaption": "Cancel",
	"Message": "Are you sure want to clear data? This will clear results, notes and attachments.",
	"OKCaption": "OK",
	"OnOK": "/SmartInspections/Rules/QualitativePFFPage_SaveValidations.rule.js",
	"Title": "CONFIRM",
	"_Type": "Action.Type.Message"
}