{
	"ActionResult": {
		"_Name": "result"
	},
	"ShowActivityIndicator": true,
	"OnFailure": "/SmartInspections/Actions/ODataFailure_ErrorMessage.action",
	"OnSuccess": "/SmartInspections/Actions/Save_InProgressMessage.action",
	"Properties": {
		"FixedValuesResult": "{FixedValuesResult}"
	},
	"RequestOptions": {
		"UpdateMode": "Replace"
	},
	"Target": {
		"EntitySet": "InspectionCharacteristicDetailsSet",
		"ReadLink": "{@odata.readLink}",
		"Service": "/SmartInspections/Services/SAM.service"
	},
	"_Type": "Action.Type.ODataService.UpdateEntity"
}