{
	"OnFailure": "/SmartInspections/Actions/QualitativeDateSave_FailureMessage.action",
	"OnSuccess": "/SmartInspections/Rules/QualitativeDateUpdateEntity_Success.js",
	"Properties": {
		"DateResult": "#Control:QualitativeReading/#Value",
		"FixedValuesResult": "#Control:Status/#SelectedValue",
		"LongText": "/SmartInspections/Rules/InspectionCharacteristicDetailsSaveLongText_GetValue.rule.js"
	},
	"RequestOptions": {
		"UpdateMode": "Replace"
	},
	"Target": {
		"EntitySet": "InspectionCharacteristicDetailsSet",
		"ReadLink": "{@odata.readLink}",
		"Service": "/SmartInspections/Services/SAM.service"
	},
	"_Type": "Action.Type.ODataService.UpdateEntity"
}