{
	"CancelCaption": "Cancel",
	"Message": "Value outside thresholds. Do you want to continue the save?",
	"OKCaption": "OK",
	"OnOK": "/SmartInspections/Actions/QuantitativeMultipleSave_UpdateEntity.action",
	"ShowActivityIndicator": false,
	"Title": "WARNING",
	"_Type": "Action.Type.Message"
}