{
	"_Type": "Action.Type.ToastMessage",
	"OnSuccess": "/SmartInspections/Rules/AutoSync/SIApplicationAfterStartUp.js",
	"Message": "SI Application Initialized",
	"NumberOfLines": 2,
	"Duration": 3,
	"IsIconHidden": false,
	"Animated": true
}