{
	"_Type": "Action.Type.ToastMessage",
	"OnSuccess": "/SmartInspections/Rules/AutoSync/SIApplicationAfterSync.js",
	"Message": "SI Sync Successful",
	"NumberOfLines": 2,
	"Duration": 3,
	"IsIconHidden": false,
	"Animated": true
}