{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "result"
	},
	"OnFailure": "/SmartInspections/Actions/TechnicalObject_CreateEntity_ErrorMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Saving in-progress...",
	"Target": {
		"EntitySet": "TechnicalObjectDetailsSet",
		"Service": "/SmartInspections/Services/SAM.service"
	},
	"Properties": {
		"AbcIndicator": "{AbcIndicator}",
		"CatalogProfile": "{CatalogProfile}",
		"AdhocFlag": "{AdhocFlag}",
		"ChangedBy": "{ChangedBy}",
		"ChangedByAlias": "{ChangedByAlias}",
		"ChangedOn": "{ChangedOn}",
		"ChangedTime": "{ChangedTime}",
		"DescopedBy": "{DescopedBy}",
		"DescopedByAlias": "{DescopedByAlias}",
		"DescopeType": "{DescopeType}",
		"DescopeTypeDesc": "{DescopeTypeDesc}",
		"Equipment": "{Equipment}",
		"EquipmentDescription": "{EquipmentDescription}",
		"EquipmentFlag": "{EquipmentFlag}",
		"FunctionalLocation": "{FunctionalLocation}",
		"FunctionalLocationDesc": "{FunctionalLocationDesc}",
		"InspectionLotNumber": "{InspectionLotNumber}",
		"InspectionSampleNumber": "{InspectionSampleNumber}",
		"InspectionType": "{InspectionType}",
		"InspectionTypeDesc": "{InspectionTypeDesc}",
		"InspectionTypeOrg": "{InspectionTypeOrg}",
		"InspectionTypeOrgDesc": "{InspectionTypeOrgDesc}",
		"IsAdhocAdded": "{IsAdhocAdded}",
		"LastInspLotNumber": "{LastInspLotNumber}",
		"LastInspType": "{LastInspType}",
		"LastInspTypeDesc": "{LastInspTypeDesc}",
		"LastOrderNumber": "{LastOrderNumber}",
		"ListCounter": "{ListCounter}",
		"NodeNumber": "{NodeNumber}",
		"OperationNumber": "{OperationNumber}",
		"OrderDescription": "{OrderDescription}",
		"OrderNumber": "{OrderNumber}",
		"OrderType": "{OrderType}",
		"SaveMode": "{SaveMode}",
		"SelectedToSave": "{SelectedToSave}",
		"SortNumber": "{SortNumber}",
		"Status": "{Status}",
		"TechnicalObject": "{TechnicalObject}",
		"TotalFail": "{TotalFail}",
		"TotalFix": "{TotalFix}",
		"TotalPass": "{TotalPass}",
		"TotalPending": "{TotalPending}",
		"UsageDecisionCode": "{UsageDecisionCode}",
		"ExGrp": "{ExGrp}",
		"ExGrpDesc": "{ExGrpDesc}",
		"ExGrpOrg": "{ExGrpOrg}",
		"ExGrpOrgDesc": "{ExGrpOrgDesc}",
		"EXNodeNumber": "{EXNodeNumber}",
		"EXOperationNumber": "{EXOperationNumber}"
	},
	"RequestOptions": {
		"RemoveCreatedEntityAfterUpload": true
	}
}