{
	"OnFailure": "/SmartInspections/Actions/TechnicalObjectSave_FailureMessage.action",
	"Properties": {
		"SaveMode": "{SaveMode}",
		"SelectedToSave": "{SelectedToSave}",
		"Status": "{Status}"
	},
	"RequestOptions": {
		"UpdateMode": "Replace"
	},
	"Target": {
		"EntitySet": "TechnicalObjectDetailsSet",
		"ReadLink": "{@odata.readLink}",
		"Service": "/SmartInspections/Services/SAM.service"
	},
	"_Type": "Action.Type.ODataService.UpdateEntity"
}