{
	"_Type": "Action.Type.PopoverMenu",
	"ActionResult": {
		"_Name": "config"
	},
	"Title": "Select Template",
	"Message": "Select the Required Text Template",
	"PopoverItems": [
		{
			"Title": "Dummy",
			"Icon": "",
			"Style": "",
			"OnPress": "A",
			"Visible": true,
			"Enabled": true
		}
	]
}