{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "OpenTechObjHeaderNotesPage"
	},
	"PageToOpen": "/SmartInspections/Pages/TextTemplates/TechObjectHeaderNotes.page",
	"BackStackVisible": true,
	"ModalPage": true,
	"NavigationType": "Outer",
	"Transition": {
		"Curve": "EaseIn",
		"Duration": 2,
		"Name": "Flip"
	}
}