{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "TechObjecHeaderNote_CancelPrompt"
	},
	"Message": "Are you sure want to cancel without saving the changes?",
	"Title": "Cancel Changes",
	"OKCaption": "Yes, Cancel",
	"OnOK": "/SmartInspections/Actions/TextTemplates/ClosePage.action",
	"CancelCaption": "No, Let Me Review"
}