{
	"_Type": "Action.Type.ToastMessage",
	"ActionResult": {
		"_Name": "TechnicalObjectLTLongText_UE_Success"
	},
	"OnSuccess": "/SmartInspections/Actions/TextTemplates/ClosePage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Redirecting to Equipment View...",
	"Message": "Technical Object Header Notes Updated",
	"NumberOfLines": 2,
	"Icon": "sap-icon://message-success",
	"Animated": true
}