{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "TechnicalObjectLTLongText_UpdateEntity"
	},
	"OnFailure": "/SmartInspections/Actions/TextTemplates/TechnicalObjectLTLongText_UE_Failure.action",
	"OnSuccess": "/SmartInspections/Actions/TextTemplates/TechnicalObjectLTLongText_UE_Success.action",
	"Target": {
		"Service": "/SmartInspections/Services/SAM.service",
		"EntitySet": "TechnicalObjectDetailsSet",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"Status": "{Status}",
		"IsLTUpdated": "{IsLTUpdated}",
		"LTTemplateID": "{LTTemplateID}",
		"LTLongText": "{LTLongText}",
		"LTChangedBy": "{LTChangedBy}",
		"LTChangedOn": "{LTChangedOn}",
		"LTChangeTime": "{LTChangeTime}"
	},
	"RequestOptions": {
		"UpdateMode": "Replace"
	}
}